### ISSUE TITLE
figure and paragraph indent conflict?

### ISSUE THREAD

**Issue by bdarcus** [matejlatin/Gutenberg#55]
If I set paragraph indenting to true, I get some unexpected behavior on some paragraphs. Example (note "With this invention ...".

![image](https://cloud.githubusercontent.com/assets/1134/19020607/c37ded58-887b-11e6-8e33-4c636be3d0cb.png)

**Comment by matejlatin** [comment]
Yup, looks like a bug. There's an image before the paragraph so the p + p css rule doesn't apply. We'll have to fix this.

**Comment by jameskolce** [comment]
Change this block:

```scss
@if $paragraph-indent == true {

  p + p {
    @include margin-top(-1);
    text-indent: #{ $leading + 'px'};
    text-indent: #{ $leading-rem + 'rem'};

    .floatLeft + p,
    .floatRight + p {

      @media screen and (min-width: #{ $max-width + 5 + 'em'}) {
        $leading: $leading-desktop;
        $leading-rem: $leading-rem-desktop;

        text-indent: #{ $leading + 'px'};
        text-indent: #{ $leading-rem + 'rem'};
      }

    }

  }

  .attention-grabber + p {
    margin-top: 0;
    text-indent: 0;
  }
}
```

To this:

```scss
@if $paragraph-indent == true {

  p + p {
    @include margin-top(-1);
    text-indent: #{ $leading + 'px'};
    text-indent: #{ $leading-rem + 'rem'};
  }

  .floatLeft + p,
  .floatRight + p {

    @media screen and (min-width: #{ $max-width + 5 + 'em'}) {
      $leading: $leading-desktop;
      $leading-rem: $leading-rem-desktop;

      text-indent: #{ $leading + 'px'};
      text-indent: #{ $leading-rem + 'rem'};
    }
  }

  .attention-grabber + p {
    margin-top: 0;
    text-indent: 0;
  }
}
```

File _text.scss line 77–103
